// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import importX from 'eslint-plugin-import-x';
import prettier from 'eslint-config-prettier';

/**
 * Module-boundary enforcement.
 *
 * A module (apps/api/src/modules/<name>/) exposes exactly one public surface:
 * its own index.ts. Other modules import that and nothing else.
 *
 * This is enforced by the build, not by discipline. UIFP kept its dependency
 * graph honest by convention alone and it still drifted — see the architecture
 * discussion document, risk D4.
 */
const CROSS_MODULE_MESSAGE =
  'Do not reach into another module. Import its index — "../<name>" — and if what you need is not exported there, it is not public API.';

/**
 * Boundary rules, scoped by where the file lives.
 *
 * src/modules/<name>/  a business module. Its index.ts is its only public
 *                      surface. Sibling modules may not reach past it.
 * src/shared/          cross-cutting infrastructure (logging, errors, database,
 *                      request context). Freely importable by anything — that
 *                      is its purpose — and internally unrestricted.
 *
 * Enforced by the build rather than by review. The reference codebase kept its
 * dependency graph honest by convention alone and it still drifted.
 */
const moduleInternalsRule = {
  'no-restricted-imports': [
    'error',
    {
      patterns: [
        {
          // One "../" followed by a directory and something beyond it: that is a
          // sibling module's internals.
          //
          //   ../projects            allowed  — the module's public index
          //   ../projects/service    blocked  — reaching past the index
          //   ../../shared/logging   allowed  — shared infrastructure, not a module
          //
          // Written as a regex rather than a glob because the glob matcher
          // treats "*" as able to match "..", which silently caught every
          // shared/ import too.
          regex: String.raw`^\.\./(?!\.\.)[^/]+/.+`,
          message: CROSS_MODULE_MESSAGE,
        },
      ],
    },
  ],
};

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.next/**',
      '**/coverage/**',
      // Generated by Prisma — not ours to lint.
      '**/src/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.strict,
  ...tseslint.configs.stylistic,

  {
    files: ['**/*.ts', '**/*.tsx', '**/*.mts'],
    plugins: { 'import-x': importX },
    rules: {
      // A cycle between modules means the boundary is wrong. Fail the build.
      'import-x/no-cycle': ['error', { maxDepth: Infinity }],

      // Import order makes a file's dependency layer readable from the top.
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          pathGroups: [{ pattern: '@/**', group: 'internal', position: 'before' }],
          pathGroupsExcludedImportTypes: ['builtin'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],

      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // Boundary enforcement applies to business modules only.
  {
    files: ['apps/api/src/modules/**/*.ts'],
    rules: moduleInternalsRule,
  },

  // NestJS resolves constructor dependencies from the metadata TypeScript emits
  // for decorated classes. An `import type` erases the class at runtime, so the
  // metadata becomes undefined and injection fails — at startup, with an opaque
  // message. `consistent-type-imports` would auto-"fix" working code into that
  // state, so it stays off for the API.
  {
    files: ['apps/api/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },

  // NestJS module classes are declarative and legitimately empty — the
  // decorator is the content. This is not a code smell here.
  {
    files: ['**/*.module.ts'],
    rules: { '@typescript-eslint/no-extraneous-class': 'off' },
  },

  // Tests are linted too — UIFP left them out and they drifted.
  {
    files: ['**/*.test.ts', '**/*.spec.ts', '**/tests/**'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },

  // Tooling that runs on a bare machine: the setup script and this config.
  //
  // These are plain JavaScript on purpose. The setup script has to run BEFORE
  // `pnpm install` has ever been run, so it cannot be compiled and cannot use a
  // dependency — including @types/node, which is why Node's own globals have to
  // be declared here for it.
  {
    files: ['scripts/**/*.mjs', 'eslint.config.mjs'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', URL: 'readonly' },
    },
  },

  prettier,
);
